name: smodi
description: 'Your AI-Powered Focus & Wellness Coach.'
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # handling deep links (app URLs)
  app_links: ^3.5.0

  # Core & Utilities
  cupertino_icons: ^1.0.6
  get_it: ^7.6.7 # Dependency Injection
  flutter_dotenv: ^5.1.0 # For environment variables

  # State Management
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  # UI & Animations
  flutter_animate: ^4.5.0 # For beautiful, simple animations
  google_fonts: ^6.2.1 # For custom fonts

  # Database & Networking
  supabase_flutter: ^2.5.0 # Supabase client for auth and DB
  sqflite: ^2.3.3 # Local SQLite database
  sqflite_common_ffi: ^2.3.3
  path_provider: ^2.1.3 # For finding local DB path
  socket_io_client: ^2.0.3+1 # Real-time communication
  http: ^1.2.1 # For basic HTTP requests (IoT fallback)

  # AI & Camera
  tflite_flutter: ^0.10.4 # On-device AI
  google_ml_kit: ^0.16.0 # For pre-built AI tasks if needed
  camera: ^0.11.0 # For camera access (if not using IoT stream exclusively)

  # Other
  intl: ^0.19.0 # For date/time formatting

  # UUID generation
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.7 # For testing BLoCs
  mocktail: ^1.0.3 # For mocking dependencies in tests
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/images/
  #   - assets/models/  # For TFLite models

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
