name: smodi
description: 'Your AI-Powered Focus & Wellness Coach.'
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core & Utilities
  cupertino_icons: ^1.0.6
  get_it: ^7.6.7
  flutter_dotenv: ^5.1.0
  uuid: ^4.4.0
  permission_handler: ^11.3.1 # For microphone permissions

  # State Management
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  # UI & Animations
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0 # For charts

  # Database & Networking
  supabase_flutter: ^2.5.0
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  path_provider: ^2.1.3
  http: ^1.2.1
  connectivity_plus: ^6.0.3
  flutter_secure_storage: ^9.2.2
  web_socket_channel: ^3.0.3
  web_socket_client: ^0.2.1

  # Deep Linking
  # uni_links: ^0.5.1

  # Audio
  flutter_sound: ^9.3.0
  audioplayers: ^6.0.0

  # Screen Capture & Sharing
  screenshot: ^3.0.0
  share_plus: ^9.0.0

  # QR Code and Barcode Scanning
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1

  # Communication
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  network_info_plus: ^5.0.3

  # Other
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  logger: ^2.5.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.7 # For testing BLoCs
  mocktail: ^1.0.3 # For mocking dependencies in tests
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/images/
  #   - assets/models/  # For TFLite models

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
